jobs:
  - job: BazelBuildServingTensorFlowGPU
    displayName: Bazel build serving (TensorFlow GPU)
    condition: and(succeeded(), eq(dependencies.BazelBuildServingTensorFlowCheck.outputs['TensorflowBuildCheck.BuildTensorFlow'], 'true'))
    dependsOn: BazelBuildServingTensorFlowCheck
    pool:
        vmImage: Ubuntu-18.04
    timeoutInMinutes: 0
    steps:
      - template: ../steps/intsall-tf-serving-gpu-deps.yml
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
