jobs:
  - job: BazelBuildServingDemo
    displayName: Bazel build serving demo
    pool:
        vmImage: Ubuntu-20.04
    timeoutInMinutes: 0
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: pip install -U numpy six
        displayName: Install additional dependencies
      - template: ../steps/use-build-cache.yml
        parameters:
            key: bazel-build-serving-demo
            path: $(BAZEL_BUILD_CACHE)
      - script: |
            bazel build //adlik_serving/demo \
                --config=tensorflow-lite-cpu \
                -c opt \
                --disk_cache="$BAZEL_BUILD_CACHE"
        displayName: Bazel build serving demo
  - job: BazelBuildServingDemoAArch64
    displayName: Bazel build serving demo (AArch64)
    pool:
        vmImage: Ubuntu-20.04
    timeoutInMinutes: 0
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: pip install -U numpy six
        displayName: Install additional dependencies
      - template: ../steps/use-build-cache.yml
        parameters:
            key: bazel-build-serving-demo-aarch64
            path: $(BAZEL_BUILD_CACHE)
      - script: |
            bazel build //adlik_serving/demo \
                --config=tensorflow-lite-cpu \
                --config=aarch64 \
                -c opt \
                --disk_cache="$BAZEL_BUILD_CACHE"
        displayName: Bazel build serving demo (AArch64)
