jobs:
  - job: BazelLongTimeBuildCheck
    displayName: Bazel long time build check
    pool:
        vmImage: Ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: ci/checks/bazel-long-time-build-check.py $SOURCE_BRANCH_NAME
        name: BuildCheck
        displayName: Bazel long time build check
