jobs:
  - job: BazelBuildServingTensorFlowGPU
    displayName: Bazel build serving (TensorFlow GPU)
    pool:
        vmImage: Ubuntu-18.04
    timeoutInMinutes: 0
    steps:
      - template: ../steps/install-cuda.yml
      - script: |
            sudo apt-get install --no-install-recommends -y \
                libnvinfer7=7.2.*+cuda11.0 \
                libnvinfer-dev=7.2.*+cuda11.0 \
                libnvinfer-plugin7=7.2.*+cuda11.0 \
                libnvinfer-plugin-dev=7.2.*+cuda11.0
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: pip install -U numpy six
        displayName: Install additional dependencies
      # - template: ../steps/use-build-cache.yml
      #   parameters:
      #       key: bazel-build-serving-tensorflow-gpu
      #       path: $(BAZEL_BUILD_CACHE)
      - script: |
            env TF_CUDA_VERSION=11.0 TF_NEED_TENSORRT=1 \
                ci/checks/bazel-build-serving.py \
                    --config=tensorflow-gpu \
                    -c opt \
                    --disk_cache="$BAZEL_BUILD_CACHE"
        displayName: Bazel build serving
      - task: PublishBuildArtifacts@1
        displayName: Publish build artifacts
        inputs:
            pathtoPublish: __adlik_serving/adlik_serving
            artifactName: adlik-serving-tensorflow-gpu
