jobs:
  - job: Buildifier
    displayName: Buildifier
    pool:
        vmImage: ubuntu-latest
    steps:
      - template: ci/azure-pipelines/install-buildifier.yml
      - script: ci/checks/buildifier.py
        displayName: Run Buildifier
