jobs:
  - job: Buildifier
    displayName: Buildifier
    pool:
        vmImage: ubuntu-latest
    steps:
      - template: ../steps/useinstall-buildifier.yml
      - script: ci/checks/buildifier.py
        displayName: Run Buildifier
