jobs:
  - job: Buildifier
    displayName: Buildifier
    pool:
        vmImage: Ubuntu-18.04
    steps:
      - template: ../steps/install-buildifier.yml
      - script: buildifier -lint warn -mode check -r .
        displayName: Run Buildifier
