jobs:
  - job: ClangFormat
    displayName: Clang-Format
    pool:
        vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        displayName: Use latest Python
      - script: ci/checks/clang-format.py
        displayName: Run Clang-Format
