jobs:
  - job: ClangFormat
    displayName: Clang-Format
    pool:
        vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: ci/checks/clang-format.py
        displayName: Run Clang-Format
