jobs:
  - job: CommitMessage
    displayName: Commit message
    pool:
        vmImage: Ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: ci/checks/commit-message.py
        displayName: Check commit message
