jobs:
  - job: Copyright
    displayName: Copyright
    pool:
        vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: ci/checks/copyright.py
        displayName: Check copyright notations
