jobs:
  - job: Flake8
    displayName: Flake8
    pool:
        vmImage: Ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: python3 -m pip install -U flake8
        displayName: Install Flake8
      - script: ci/checks/flake8.py
        displayName: Run Flake8
