jobs:
  - job: Flake8
    displayName: Flake8
    pool:
        vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        displayName: Use latest Python
      - script: python3 -m pip install -U flake8
        displayName: Install Flake8
      - script: ci/checks/flake8.py
        displayName: Run Flake8
