jobs:
  - job: Markdownlint
    displayName: Markdownlint
    pool:
        vmImage: ubuntu-latest
    steps:
      - script: npm install -g markdownlint-cli
        displayName: Install markdownlint-cli
      - script: markdownlint '**/*.md'
        displayName: Run markdownlint
