jobs:
  - job: Markdownlint
    displayName: Markdownlint
    pool:
        vmImage: ubuntu-latest
    steps:
      - script: sudo npm install -g markdownlint-cli
        displayName: Install markdownlint-cli
      - script: markdownlint '**/*.md' -c .markdownlint.json
        displayName: Run markdownlint
