jobs:
  - job: ToxBenchmark
    displayName: Tox benchmark
    pool:
        vmImage: Ubuntu-18.04
    timeoutInMinutes: 0
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Install Python3.8
      - script: pip install -U tox
        displayName: Install tox
      - script: cd benchmark && tox
        displayName: Run tox
