jobs:
  - job: ToxModelCompiler
    displayName: Tox model compiler
    pool:
        vmImage: Ubuntu-18.04
    steps:
      - template: ../steps/install-tensorrt.yml
      - template: ../steps/install-openvino-compiler.yml
      - script: sudo apt-get install -y libquadmath0
        displayName: Install libquadmath0
      - script: sudo ldconfig -v | grep -i libquadmath
        displayName: Run ldconfig
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
        displayName: Install Python3.6
      - script: pip install -U tox
        displayName: Install tox
      - script: sudo apt-get install --no-install-recommends -y protobuf-compiler
        displayName: Install Protocol Buffers
      - script: tox -e py36-cpu
        displayName: Run tox
        workingDirectory: model_compiler
