jobs:
  - job: ToxModelCompiler
    displayName: Tox model compiler
    pool:
        vmImage: ubuntu-latest
    steps:
      - template: ../steps/install-tensorrt.yml
      - template: ../steps/install-openvino-compiler.yml
      - task: UsePythonVersion@0
        displayName: Use Python 3.6
        inputs:
            versionSpec: '3.6'
      - script: pip install -U tox
        displayName: Install tox
      - script: sudo apt-get install --no-install-recommends -y protobuf-compiler
        displayName: Install Protocol Buffers
      - script: tox -e py36-cpu
        displayName: Run tox
        workingDirectory: model_compiler
