jobs:
  - job: ToxModelCompiler
    displayName: Tox model compiler
    pool:
        vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        displayName: Use Python 3.6
        inputs:
            versionSpec: '3.6'
      - script: pip install -U tox
        displayName: Install tox
      - script: cd model_compiler && tox
        displayName: Run tox
