load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "env",
    hdrs = ["env.h"],
    deps = ["//cub/dci"],
)
