load("//adlik_serving:serving.bzl", "serving_cc_library")

serving_cc_library(
    name = "tensorflow_lite_runtime",
    srcs = ["tensorflow_lite_runtime.cc"],
    visibility = ["//adlik_serving:internal"],
    alwayslink = 1,
)
