steps:
  - script: |
        set -e
        curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
        sudo add-apt-repository 'deb https://storage.googleapis.com/bazel-apt/ stable jdk1.8'
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y bazel
    displayName: Install Bazel
