steps:
  - script: |
        set -e
        . /etc/os-release
        curl "https://developer.download.nvidia.com/compute/cuda/repos/$ID$(echo $VERSION_ID | tr -d .)/x86_64/7fa2af80.pub" | sudo apt-key add -
        sudo apt-add-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/$ID$(echo $VERSION_ID | tr -d .)/x86_64 /"
        sudo apt-add-repository -u "deb https://developer.download.nvidia.com/compute/machine-learning/repos/$ID$(echo $VERSION_ID | tr -d .)/x86_64 /"
        sudo apt-get install --no-install-recommends -y \
            cuda-cupti-dev-11-0 \
            libcublas-dev-11-0 \
            libcufft-dev-11-0 \
            libcurand-dev-11-0 \
            libcusolver-dev-11-0 \
            libcusparse-dev-11-0 \
            'libcudnn8=*+cuda11.0' \
            'libcudnn8-dev=*+cuda11.0'
    displayName: Install CUDA libraries
