steps:
  - script: |
        set -e
        clang_version=$(clang --version | grep -m 1 -oP '(?<=^clang version )\d+')
        sudo apt-get install --no-install-recommends -y "clang-format-$clang_version"
        sudo update-alternatives --install /usr/bin/clang-format clang-format "/usr/bin/clang-format-$clang_version" 100
    displayName: Install Clang-Format
