steps:
  - script: |
        set -e
        sudo apt-get update 
        sudo apt-get install --no-install-recommends -y \
        libpng-dev \
        libjpeg-dev \
        libgomp1
        sudo apt-get install --no-install-recommends -y wget unzip
        wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip"
        sudo unzip -d / libtorch-cxx11-abi-shared-with-deps-1.8.1+cpu.zip 
        sudo rm libtorch-cxx11-abi-shared-with-deps-1.8.1+cpu.zip 
        wget "https://github.com/pytorch/vision/archive/refs/tags/v0.9.1.zip" 
        sudo unzip v0.9.1.zip 
        sudo rm -f v0.9.1.zip
        cd vision-0.9.1 && sudo mkdir build && cd build
        sudo mkdir /vision-0.9.1
        sudo cmake -DCMAKE_PREFIX_PATH=/libtorch -DCMAKE_INSTALL_PREFIX=/vision-0.9.1 -DCMAKE_BUILD_TYPE=Release .. 
        sudo cmake --build . && sudo make install
        cd ../..
        wget "https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcu102.zip"
        sudo rm -rf /libtorch 
        sudo unzip -d / libtorch-cxx11-abi-shared-with-deps-1.8.1+cu102.zip 
        sudo rm libtorch-cxx11-abi-shared-with-deps-1.8.1+cu102.zip 

    displayName: Build and install Torch
