steps:
  - script: |
        sudo apt-get update && sudo apt-get install -y libedit-dev libxml2-dev
        git clone --recursive --single-branch --branch v0.7 https://github.com/apache/tvm.git
        mkdir tvm/build && cp tvm/cmake/config.cmake tvm/build
        cmake -Stvm -Btvm/build
        sudo cmake --build tvm/build --parallel 16 --target install
        sudo cp -r tvm/3rdparty/dlpack/include/dlpack /usr/local/include
        sudo rm -rf tvm
    displayName: Build and install Tvm