// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: adlik_serving/apis/get_model_meta.proto
#ifndef GRPC_adlik_5fserving_2fapis_2fget_5fmodel_5fmeta_2eproto__INCLUDED
#define GRPC_adlik_5fserving_2fapis_2fget_5fmodel_5fmeta_2eproto__INCLUDED

#include "adlik_serving/apis/get_model_meta.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace adlik {
namespace serving {

}  // namespace serving
}  // namespace adlik


#endif  // GRPC_adlik_5fserving_2fapis_2fget_5fmodel_5fmeta_2eproto__INCLUDED
