// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adlik_serving/apis/predict_service.proto

#include "adlik_serving/apis/predict_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace adlik {
namespace serving {
}  // namespace serving
}  // namespace adlik
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n(adlik_serving/apis/predict_service.pro"
  "to\022\radlik.serving\032 adlik_serving/apis/pr"
  "edict.proto\032\'adlik_serving/apis/get_mode"
  "l_meta.proto2\263\001\n\016PredictService\022H\n\007predi"
  "ct\022\035.adlik.serving.PredictRequest\032\036.adli"
  "k.serving.PredictResponse\022W\n\014getModelMet"
  "a\022\".adlik.serving.GetModelMetaRequest\032#."
  "adlik.serving.GetModelMetaResponseB\003\370\001\001b"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_deps[2] = {
  &::descriptor_table_adlik_5fserving_2fapis_2fget_5fmodel_5fmeta_2eproto,
  &::descriptor_table_adlik_5fserving_2fapis_2fpredict_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_once;
static bool descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto = {
  &descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_initialized, descriptor_table_protodef_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto, "adlik_serving/apis/predict_service.proto", 327,
  &descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_once, descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_sccs, descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto_deps, 0, 2,
  schemas, file_default_instances, TableStruct_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto::offsets,
  file_level_metadata_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto, 0, file_level_enum_descriptors_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto, file_level_service_descriptors_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_adlik_5fserving_2fapis_2fpredict_5fservice_2eproto), true);
namespace adlik {
namespace serving {

// @@protoc_insertion_point(namespace_scope)
}  // namespace serving
}  // namespace adlik
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
